# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-05-05 17:03
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='education',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Degree', models.CharField(help_text='Enter the Degree/Doploma/Certificate', max_length=50)),
                ('Institute', models.CharField(help_text='Enter the Institute/University', max_length=50)),
                ('From', models.DateField(help_text='Enter the starting date of your degree')),
                ('To', models.DateField(help_text='Enter the ending date of your degree')),
                ('Percentage', models.IntegerField(help_text='Enter the final Percentage(%)')),
            ],
        ),
        migrations.CreateModel(
            name='emergency',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Contact_person_name', models.CharField(help_text='Enter name', max_length=50)),
                ('Relation', models.CharField(help_text='Enter the relation', max_length=50)),
                ('Landline_No', models.IntegerField(help_text='Enter Landline number')),
                ('Mobile_No', models.IntegerField(help_text='Enter Mobile number')),
            ],
        ),
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('Employee_id', models.IntegerField(help_text='Enter Employees ID', primary_key=True, serialize=False)),
                ('Employee_name', models.CharField(help_text='Enter Employees Name', max_length=50)),
                ('Fathers_name', models.CharField(help_text='Enter Fathers Name', max_length=50)),
                ('Date_Of_Birth', models.DateField(help_text='Enter Employees Date of Birth')),
                ('Gender', models.CharField(choices=[('', ''), ('Male', 'Male'), ('Female', 'Female')], help_text='Choose Employees Gender', max_length=50)),
                ('Present_Address', models.TextField(help_text='Enter Employees Present Address')),
                ('Permanent_Address', models.TextField(help_text='Enter Employees Permanent Address')),
                ('Residential_Contact_No', models.IntegerField(help_text='Enter Employees Residential Contact No.')),
                ('Permanent_Contact_No', models.IntegerField(help_text='Enter Employees Permanent Contact No.')),
                ('Email_id', models.EmailField(help_text='Enter Employees Email Id', max_length=50, null=True)),
                ('Marital_Status', models.CharField(choices=[('', ''), ('Married', 'Married'), ('Single', 'Single'), ('Divorcee', 'Divorcee')], help_text='Choose Employees Marital Status', max_length=50)),
                ('Marriage_Date', models.DateField(help_text='Enter Employees Marriage Date')),
            ],
        ),
        migrations.CreateModel(
            name='employment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Date_of_Joining', models.DateField(help_text='Enter date of joining')),
                ('Date_of_Resigning', models.DateField(default='2011-01-16', help_text='Enter the resigning date')),
                ('Location', models.CharField(default='0', help_text='Enter the location working on', max_length=50)),
                ('Last_working_day', models.DateField(default='2011-01-16', help_text='Enter the last day of working')),
                ('Department', models.CharField(help_text='Enter the belonging department', max_length=50)),
                ('Designation', models.CharField(help_text='Enter the belomging designation', max_length=50)),
                ('Pan_no', models.CharField(help_text='Enter your Pan No.', max_length=50)),
                ('Epic_no', models.CharField(help_text='Enter your Epic No.', max_length=50)),
                ('Aadhar_card_no', models.CharField(help_text='Enter Aadhar Card No.', max_length=50)),
                ('Bank_acc_no', models.IntegerField(help_text='Enter the Bank Account Number')),
                ('PF_acc_no', models.IntegerField(help_text='Enter the Provident Fund Acccount Number')),
                ('UAN_No', models.IntegerField(default='0', help_text='Enter the UAN No.')),
                ('ESIC_no', models.IntegerField(help_text='Enter the ESIC number')),
                ('Reporting_person', models.CharField(help_text='Enter the name of reporting person', max_length=50)),
                ('Joining_Salary', models.IntegerField(help_text='Enter the joining Salary')),
                ('Present_Salary', models.IntegerField(help_text='Enter the present Salary')),
                ('Transfer_date', models.DateField(default='2011-01-16', help_text='Enter the date of transfer')),
                ('Transfer_to', models.CharField(default='0', help_text='Enter the place transferred to.', max_length=50)),
                ('Last_date_of_increment', models.DateField(help_text='Enter last date of increment')),
                ('Employee_Status', models.CharField(choices=[('', ''), ('Active', 'Active'), ('Left', 'Left')], help_text='Enter the employment status of employee.', max_length=50)),
                ('Employee_id', models.ForeignKey(help_text='Choose for which employee you want to enter details', on_delete=django.db.models.deletion.CASCADE, to='personal.Employee')),
            ],
        ),
        migrations.CreateModel(
            name='family',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(help_text='Enter name.', max_length=50)),
                ('Date_of_Birth', models.DateField(help_text='Enter Date Of Birth')),
                ('Gender', models.CharField(choices=[('', ''), ('Male', 'Male'), ('Female', 'Female')], help_text='Enter the gender.', max_length=50)),
                ('Relationship', models.CharField(help_text='Enter the relationship.', max_length=50)),
                ('Occupation', models.CharField(help_text='Enter occupation.', max_length=50)),
                ('Employee_id', models.ForeignKey(help_text='Choose for which employee you want to enter details', on_delete=django.db.models.deletion.CASCADE, to='personal.Employee')),
            ],
        ),
        migrations.CreateModel(
            name='med',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Blood_group', models.CharField(choices=[('A+', 'A+'), ('A-', 'A-'), ('B+', 'B+'), ('B-', 'B-'), ('AB+', 'AB+'), ('AB-', 'AB-'), ('O+', 'O+'), ('O-', 'O-')], help_text='Enter the Blood Group', max_length=50)),
                ('Ailments', models.CharField(help_text='Enter Ailments(Heart condition,BP etc.) if any', max_length=50)),
                ('Allergies', models.CharField(help_text='Enter the allergies(Drug, etc.) if any', max_length=50)),
                ('Employee_id', models.ForeignKey(help_text='Choose for which employee you want to enter details', on_delete=django.db.models.deletion.CASCADE, to='personal.Employee')),
            ],
        ),
        migrations.CreateModel(
            name='references',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(help_text='Enter the references name', max_length=50)),
                ('Contact_No', models.IntegerField(help_text='Enter the references contact number')),
                ('Employee_id', models.ForeignKey(help_text='Choose for which employee you want to enter details', on_delete=django.db.models.deletion.CASCADE, to='personal.Employee')),
            ],
        ),
        migrations.AddField(
            model_name='emergency',
            name='Employee_id',
            field=models.ForeignKey(help_text='Choose for which employee you want to enter details', on_delete=django.db.models.deletion.CASCADE, to='personal.Employee'),
        ),
        migrations.AddField(
            model_name='education',
            name='Employee_id',
            field=models.ForeignKey(help_text='Choose for which employee you want to enter details', on_delete=django.db.models.deletion.CASCADE, to='personal.Employee'),
        ),
    ]
