# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-05-05 17:04
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('personal', '0002_auto_20170505_2234'),
    ]

    operations = [
        migrations.AddField(
            model_name='employment',
            name='Date_of_Resigning',
            field=models.DateField(default='2011-01-16', help_text='Enter the resigning date'),
        ),
        migrations.AddField(
            model_name='employment',
            name='Last_working_day',
            field=models.DateField(default='2011-01-16', help_text='Enter the last day of working'),
        ),
        migrations.AddField(
            model_name='employment',
            name='Location',
            field=models.CharField(default='0', help_text='Enter the location working on', max_length=50),
        ),
        migrations.AddField(
            model_name='employment',
            name='Transfer_date',
            field=models.DateField(default='2011-01-16', help_text='Enter the date of transfer'),
        ),
        migrations.AddField(
            model_name='employment',
            name='Transfer_to',
            field=models.CharField(default='0', help_text='Enter the place transferred to.', max_length=50),
        ),
        migrations.AddField(
            model_name='employment',
            name='UAN_No',
            field=models.IntegerField(default='0', help_text='Enter the UAN No.'),
        ),
    ]
